### ISSUE TITLE
Crash at TextureCache swap.

### ISSUE THREAD

**Issue by miyu** [the-dargon-project/dargon-model-viewer#1]
Unable to reproduce.

```
System.AggregateException was unhandled
  HResult=-2146233088
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
       at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
       at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
       at System.Threading.Tasks.Task.Wait()
       at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
       at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
       at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
       at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
       at Dargon.ModelViewer.ViewModel.ViewModelBase.LoadMeshTextures(Object arg) in V:\my-repositories\dargon-root\dev\dargon-model-viewer\dargon-model-viewer\ViewModel\ViewModelBase.cs:line 153
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart(Object obj)
  InnerException: 
       HResult=-2146233079
       Message=COM Object pointer is null
       Source=SharpDX
       StackTrace:
            at SharpDX.ComObject.SharpDX.IUnknown.Release()
            at SharpDX.ComObject.Dispose(Boolean disposing)
            at SharpDX.Direct3D11.DeviceChild.Dispose(Boolean disposing)
            at SharpDX.DisposeBase.CheckAndDispose(Boolean disposing)
            at SharpDX.DisposeBase.Dispose()
            at Dargon.Renderer.TextureCache.<>c__DisplayClass7_0.<ReplaceTexture>b__0(String key, TextureAndSRV existingValue) in V:\my-repositories\dargon-root\dev\dargon-model-viewer\Dargon.Renderer\TextureCache.cs:line 52
            at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, TValue addValue, Func`3 updateValueFactory)
            at Dargon.Renderer.TextureCache.ReplaceTexture(String textureName, String newTexturePath) in V:\my-repositories\dargon-root\dev\dargon-model-viewer\Dargon.Renderer\TextureCache.cs:line 49
            at Dargon.ModelViewer.ViewModel.ViewModelBase.<>c__DisplayClass25_0.<LoadMeshTextures>b__0(String textureName) in V:\my-repositories\dargon-root\dev\dargon-model-viewer\dargon-model-viewer\ViewModel\ViewModelBase.cs:line 154
            at System.Threading.Tasks.Parallel.<>c__DisplayClass30_0`2.<ForEachWorker>b__0(Int32 i)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
            at System.Threading.Tasks.Task.InnerInvoke()
            at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
            at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
       InnerException: 
```

**Comment by miyu** [comment]
Steps taken: Load map11 dump. Only happened 1/3 times.

**Comment by miyu** [comment]
Also, there's a tiny chance we dispose of a texture after we take from the texture cache.
